name: Analyze PR

on:
  workflow_run:
    workflows:
      - 'Build'
    types:
      - completed

permissions:
  pull-requests: read
  contents: read
  checks: write

env:
  BUILD_JAVA_VERSION: '25'

jobs:
  analyze:
    name: Analyze Code
    # Only run on forks, in-repo PRs are analyzed directly
    if: github.event.workflow_run.head_repository.owner.login != 'dnsjava'
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.BUILD_JAVA_VERSION }}
          distribution: temurin

      - name: Checkout actions
        uses: actions/checkout@v6
        with:
          repository: 'dnsjava/dnsjava'
          ref: 'master'
          persist-credentials: false
          sparse-checkout: .github

      - name: Download PR number artifact
        id: get_pr_number
        #v21
        uses: dawidd6/action-download-artifact@b6e2e70617bc3265edd6dab6c906732b2f1ae151
        with:
          workflow: ${{ github.event.workflow_run.name }}
          run_id: ${{ github.event.workflow_run.id }}
          name: pr_number

      - name: Read Pull Request Number
        id: pr_number
        run: |
          PR=$(cat pr_number.txt)
          echo "pr_number=${PR}" >> "$GITHUB_OUTPUT"

      - name: Request PR data from GitHub API
        id: get_pr_data
        #v3.0.0
        uses: octokit/request-action@b91aabaa861c777dcdb14e2387e30eddf04619ae
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          route: GET /repos/{full_name}/pulls/{number}
          full_name: ${{ github.event.repository.full_name }}
          number: ${{ steps.pr_number.outputs.pr_number }}

      - name: Checkout PR Source
        uses: actions/checkout@v6
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.head_sha }}
          persist-credentials: false
          path: pr
          # for Sonar
          fetch-depth: 0
          sparse-checkout: |
            src

      - name: Get coverage
        uses: ./.github/actions/download-artifact
        with:
          path: pr
          name: merged-coverage

      - name: Get classes
        uses: ./.github/actions/download-artifact
        with:
          path: pr
          name: classes

      - name: Checkout Maven/Sonar config
        uses: actions/checkout@v6
        with:
          repository: 'dnsjava/dnsjava'
          ref: 'master'
          persist-credentials: false
          path: pr
          sparse-checkout: |
            pom.xml
            sonar-project.properties

      - name: Run SonarQube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          WF_REVISION: ${{ github.event.workflow_run.head_sha }}
          WF_PRKEY: ${{ fromJson(steps.get_pr_data.outputs.data).number }}
          WF_BRANCH: ${{ fromJson(steps.get_pr_data.outputs.data).head.ref }}
          WF_BASE: ${{ fromJson(steps.get_pr_data.outputs.data).base.ref }}
        working-directory: pr
        run: |
          mvn -B \
          -f pom.xml \
          -Dsonar.scm.revision="${WF_REVISION}" \
          -Dsonar.pullrequest.key="${WF_PRKEY}" \
          -Dsonar.pullrequest.branch="${WF_BRANCH}" \
          -Dsonar.pullrequest.base="${WF_BASE}" \
          properties:read-project-properties \
          org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
